<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-4HRJJAG" failures="1" tests="2" name="Test" time="20.223" errors="0" timestamp="2025-09-16T11:36:35 IST">
  <testcase classname="testScript.ManageCategoryTest" name="addNewCategoryInManageCategoryTest" time="11.14">
    <failure type="java.lang.AssertionError" message="After updating the category alert is not displayed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: After updating the category alert is not displayed expected [true] but found [false]
at testScript.ManageCategoryTest.addNewCategoryInManageCategoryTest(ManageCategoryTest.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- addNewCategoryInManageCategoryTest -->
  <testcase classname="testScript.ManageCategoryTest" name="uploadImageOfAnExistingCategoryInManageCategoryTest" time="2.928"/>
</testsuite> <!-- Test -->
